driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: debian-7.4

suites:
  - name: solo
    run_list:
      - recipe[boilerplate]
  - name: full
    run_list:
      - recipe[chef-dk]
      - recipe[boilerplate::apt_fast]
      - recipe[nodejs::nodejs_from_package]
      - recipe[phantomjs]
      - recipe[python]
      - recipe[apache2]
      - recipe[database::mysql]
      - recipe[mysql::server]
      - recipe[jenkins::master]
      - recipe[boilerplate]
