driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: debian-wheezy-7
    driver_config:
      box: debian-wheezy-7
      box_url: https://dl.dropboxusercontent.com/u/86066173/debian-wheezy.box
  # - name: centos-5.10

suites:
  - name: boilerplate
    run_list:
      - recipe[boilerplate]
